### ISSUE TITLE
Readme/Instruction is wrong

### ISSUE THREAD

**Issue by abssimon** [jstewart7/mmo#1]
Hello,

There is a typo

_Start the Client
cd mmo/cmd/server
go generate && go run ._

I think it should be "cd mmo/cmd/client" and when I try it (after starting the server) it panics

panic: failed to WebSocket dial: failed to send handshake request: Get "http://localhost:8000": dial tcp [::1]:8000: connectex: No connection could be made because the target machine actively refused it.
....
exit status 2

Thanks and best regards

**Comment by unitoftime** [comment]
Hi,

Thanks for the detailed issue. I'd recommend the following steps to unblock you for now:
```
cd mmo/cmd
bash run.sh
```

I had a change where I wrote a proxy service to sit in front of the game server, but I forgot to update the README to reflect the new launch command. Take a look at `cmd/run.sh` if your curious how that changes the launch command. Executing `run.sh` should launch your 3 binaries (server, proxy, and client), and then kill them all when you exit the client.

Let me know if you have any issues. I'm going to leave this open till I get a chance to update the readme.

Thanks,
Jacob

**Comment by abssimon** [comment]
Hello,

thanks for your quick reply. Yes, run.sh runs fine. :)

Best Regards

**Comment by airtonix** [comment]
well you didn't update the readme and you forgot to mentio that something called `packer` is required and perhaps even something called gotip... -_-
