### ISSUE TITLE
WebRTC crash

### ISSUE THREAD

**Issue by Its-Kenta** [jstewart7/mmo#38]
WebRTC seems to crash with given error:
`WebRTC: ICE failed, add a STUN server and see about:webrtc for more details` when switching tab and minimising browser.

**How it happened:**
Was recording screen with OBS, stopped recording, switched tab and minimised browser. Gave it a minute or two, reopened browser and switched tab back to MMO.

**Used:**
Browser: Firefox
OS: Fedora 37

**Comment by Its-Kenta** [comment]
Just experienced the crash again by simply minimising the browser.

**Comment by unitoftime** [comment]
Should be fixed now
